/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) models_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

#ifndef CASADI_PRINTF
#define CASADI_PRINTF printf
#ifndef CASADI_SNPRINTF
#define CASADI_SNPRINTF snprintf
#endif

#endif

static const casadi_int casadi_s0[15] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
static const casadi_int casadi_s1[9] = {5, 1, 0, 5, 0, 1, 2, 3, 4};
static const casadi_int casadi_s2[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s3[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s4[6] = {2, 1, 0, 2, 0, 1};

/* kin6_model:([X, Y, phi, v_x, v_y, omega, delta, tau_FL, tau_FR, tau_RL, tau_RR][11],[u_delta, u_tau_FL, u_tau_FR, u_tau_RL, u_tau_RR][5],[m, I_z, l_R, l_F, C_m0, C_r0, C_r1, C_r2, t_tau, t_delta][10],dt)->(x_next[11],[a_x, a_y][2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a7, a8, a9;
    a0=arg[0]? arg[0][0] : 0;
    a1=arg[3]? arg[3][0] : 0;
    a2=6.;
    a2=(a1/a2);
    a3=arg[0]? arg[0][3] : 0;
    a4=arg[0]? arg[0][2] : 0;
    a5=cos(a4);
    a5=(a3*a5);
    a6=arg[0]? arg[0][4] : 0;
    a7=sin(a4);
    a7=(a6*a7);
    a5=(a5-a7);
    a7=2.;
    a8=5.0000000000000000e-01;
    a9=arg[2]? arg[2][4] : 0;
    a10=arg[0]? arg[0][7] : 0;
    a11=arg[0]? arg[0][8] : 0;
    a12=(a10+a11);
    a13=arg[0]? arg[0][9] : 0;
    a12=(a12+a13);
    a14=arg[0]? arg[0][10] : 0;
    a12=(a12+a14);
    a12=(a9*a12);
    a15=(a8*a12);
    a16=arg[2]? arg[2][5] : 0;
    a17=arg[2]? arg[2][6] : 0;
    a18=(a17*a3);
    a18=(a16+a18);
    a19=arg[2]? arg[2][7] : 0;
    a20=casadi_sq(a3);
    a20=(a19*a20);
    a18=(a18+a20);
    a20=10.;
    a21=(a20*a3);
    a21=tanh(a21);
    a18=(a18*a21);
    a15=(a15-a18);
    a12=(a8*a12);
    a18=arg[0]? arg[0][6] : 0;
    a21=cos(a18);
    a21=(a12*a21);
    a15=(a15+a21);
    a21=arg[2]? arg[2][0] : 0;
    a15=(a15/a21);
    a22=arg[0]? arg[0][5] : 0;
    a23=(a6*a22);
    a15=(a15+a23);
    a23=(a1*a15);
    a23=(a23/a7);
    a23=(a3+a23);
    a24=(a1*a22);
    a24=(a24/a7);
    a24=(a4+a24);
    a25=cos(a24);
    a25=(a23*a25);
    a26=sin(a18);
    a26=(a12*a26);
    a26=(a26/a21);
    a27=(a3*a22);
    a26=(a26-a27);
    a27=(a1*a26);
    a27=(a27/a7);
    a27=(a6+a27);
    a28=sin(a24);
    a28=(a27*a28);
    a25=(a25-a28);
    a25=(a7*a25);
    a5=(a5+a25);
    a25=arg[1]? arg[1][1] : 0;
    a28=(a25-a10);
    a29=arg[2]? arg[2][8] : 0;
    a28=(a28/a29);
    a30=(a1*a28);
    a30=(a30/a7);
    a30=(a10+a30);
    a31=arg[1]? arg[1][2] : 0;
    a32=(a31-a11);
    a32=(a32/a29);
    a33=(a1*a32);
    a33=(a33/a7);
    a33=(a11+a33);
    a34=(a30+a33);
    a35=arg[1]? arg[1][3] : 0;
    a36=(a35-a13);
    a36=(a36/a29);
    a37=(a1*a36);
    a37=(a37/a7);
    a37=(a13+a37);
    a34=(a34+a37);
    a38=arg[1]? arg[1][4] : 0;
    a39=(a38-a14);
    a39=(a39/a29);
    a40=(a1*a39);
    a40=(a40/a7);
    a40=(a14+a40);
    a34=(a34+a40);
    a34=(a9*a34);
    a41=(a8*a34);
    a42=(a17*a23);
    a42=(a16+a42);
    a43=casadi_sq(a23);
    a43=(a19*a43);
    a42=(a42+a43);
    a43=(a20*a23);
    a43=tanh(a43);
    a42=(a42*a43);
    a41=(a41-a42);
    a34=(a8*a34);
    a42=arg[1]? arg[1][0] : 0;
    a43=(a42-a18);
    a44=arg[2]? arg[2][9] : 0;
    a43=(a43/a44);
    a45=(a1*a43);
    a45=(a45/a7);
    a45=(a18+a45);
    a46=cos(a45);
    a46=(a34*a46);
    a41=(a41+a46);
    a41=(a41/a21);
    a46=arg[2]? arg[2][3] : 0;
    a12=(a46*a12);
    a47=sin(a18);
    a12=(a12*a47);
    a47=arg[2]? arg[2][1] : 0;
    a12=(a12/a47);
    a48=(a1*a12);
    a48=(a48/a7);
    a48=(a22+a48);
    a49=(a27*a48);
    a41=(a41+a49);
    a49=(a1*a41);
    a49=(a49/a7);
    a49=(a3+a49);
    a50=(a1*a48);
    a50=(a50/a7);
    a50=(a4+a50);
    a51=cos(a50);
    a51=(a49*a51);
    a52=sin(a45);
    a52=(a34*a52);
    a52=(a52/a21);
    a53=(a23*a48);
    a52=(a52-a53);
    a53=(a1*a52);
    a53=(a53/a7);
    a53=(a6+a53);
    a54=sin(a50);
    a54=(a53*a54);
    a51=(a51-a54);
    a51=(a7*a51);
    a5=(a5+a51);
    a30=(a25-a30);
    a30=(a30/a29);
    a51=(a1*a30);
    a51=(a51/a7);
    a51=(a10+a51);
    a33=(a31-a33);
    a33=(a33/a29);
    a54=(a1*a33);
    a54=(a54/a7);
    a54=(a11+a54);
    a55=(a51+a54);
    a37=(a35-a37);
    a37=(a37/a29);
    a56=(a1*a37);
    a56=(a56/a7);
    a56=(a13+a56);
    a55=(a55+a56);
    a40=(a38-a40);
    a40=(a40/a29);
    a57=(a1*a40);
    a57=(a57/a7);
    a57=(a14+a57);
    a55=(a55+a57);
    a55=(a9*a55);
    a58=(a8*a55);
    a59=(a17*a49);
    a59=(a16+a59);
    a60=casadi_sq(a49);
    a60=(a19*a60);
    a59=(a59+a60);
    a60=(a20*a49);
    a60=tanh(a60);
    a59=(a59*a60);
    a58=(a58-a59);
    a55=(a8*a55);
    a59=(a42-a45);
    a59=(a59/a44);
    a60=(a1*a59);
    a60=(a60/a7);
    a60=(a18+a60);
    a61=cos(a60);
    a61=(a55*a61);
    a58=(a58+a61);
    a58=(a58/a21);
    a34=(a46*a34);
    a45=sin(a45);
    a34=(a34*a45);
    a34=(a34/a47);
    a45=(a1*a34);
    a45=(a45/a7);
    a45=(a22+a45);
    a61=(a53*a45);
    a58=(a58+a61);
    a61=(a1*a58);
    a61=(a3+a61);
    a62=(a1*a45);
    a62=(a4+a62);
    a63=cos(a62);
    a63=(a61*a63);
    a64=sin(a60);
    a64=(a55*a64);
    a64=(a64/a21);
    a65=(a49*a45);
    a64=(a64-a65);
    a65=(a1*a64);
    a65=(a6+a65);
    a66=sin(a62);
    a66=(a65*a66);
    a63=(a63-a66);
    a5=(a5+a63);
    a5=(a2*a5);
    a0=(a0+a5);
    if (res[0]!=0) res[0][0]=a0;
    a0=arg[0]? arg[0][1] : 0;
    a5=sin(a4);
    a5=(a3*a5);
    a63=cos(a4);
    a63=(a6*a63);
    a5=(a5+a63);
    a63=sin(a24);
    a23=(a23*a63);
    a24=cos(a24);
    a27=(a27*a24);
    a23=(a23+a27);
    a23=(a7*a23);
    a5=(a5+a23);
    a23=sin(a50);
    a49=(a49*a23);
    a50=cos(a50);
    a53=(a53*a50);
    a49=(a49+a53);
    a49=(a7*a49);
    a5=(a5+a49);
    a49=sin(a62);
    a49=(a61*a49);
    a62=cos(a62);
    a62=(a65*a62);
    a49=(a49+a62);
    a5=(a5+a49);
    a5=(a2*a5);
    a0=(a0+a5);
    if (res[0]!=0) res[0][1]=a0;
    a48=(a7*a48);
    a48=(a22+a48);
    a45=(a7*a45);
    a48=(a48+a45);
    a55=(a46*a55);
    a45=sin(a60);
    a55=(a55*a45);
    a55=(a55/a47);
    a45=(a1*a55);
    a45=(a22+a45);
    a48=(a48+a45);
    a48=(a2*a48);
    a4=(a4+a48);
    if (res[0]!=0) res[0][2]=a4;
    a41=(a7*a41);
    a15=(a15+a41);
    a58=(a7*a58);
    a15=(a15+a58);
    a51=(a25-a51);
    a51=(a51/a29);
    a58=(a1*a51);
    a58=(a10+a58);
    a54=(a31-a54);
    a54=(a54/a29);
    a41=(a1*a54);
    a41=(a11+a41);
    a4=(a58+a41);
    a56=(a35-a56);
    a56=(a56/a29);
    a48=(a1*a56);
    a48=(a13+a48);
    a4=(a4+a48);
    a57=(a38-a57);
    a57=(a57/a29);
    a0=(a1*a57);
    a0=(a14+a0);
    a4=(a4+a0);
    a4=(a9*a4);
    a5=(a8*a4);
    a49=(a17*a61);
    a49=(a16+a49);
    a62=casadi_sq(a61);
    a62=(a19*a62);
    a49=(a49+a62);
    a62=(a20*a61);
    a62=tanh(a62);
    a49=(a49*a62);
    a5=(a5-a49);
    a4=(a8*a4);
    a60=(a42-a60);
    a60=(a60/a44);
    a1=(a1*a60);
    a1=(a18+a1);
    a49=cos(a1);
    a49=(a4*a49);
    a5=(a5+a49);
    a5=(a5/a21);
    a65=(a65*a45);
    a5=(a5+a65);
    a15=(a15+a5);
    a15=(a2*a15);
    a3=(a3+a15);
    if (res[0]!=0) res[0][3]=a3;
    a52=(a7*a52);
    a26=(a26+a52);
    a64=(a7*a64);
    a26=(a26+a64);
    a64=sin(a1);
    a64=(a4*a64);
    a64=(a64/a21);
    a61=(a61*a45);
    a64=(a64-a61);
    a26=(a26+a64);
    a26=(a2*a26);
    a6=(a6+a26);
    if (res[0]!=0) res[0][4]=a6;
    a34=(a7*a34);
    a12=(a12+a34);
    a55=(a7*a55);
    a12=(a12+a55);
    a46=(a46*a4);
    a4=sin(a1);
    a46=(a46*a4);
    a46=(a46/a47);
    a12=(a12+a46);
    a12=(a2*a12);
    a22=(a22+a12);
    if (res[0]!=0) res[0][5]=a22;
    a59=(a7*a59);
    a43=(a43+a59);
    a60=(a7*a60);
    a43=(a43+a60);
    a42=(a42-a1);
    a42=(a42/a44);
    a43=(a43+a42);
    a43=(a2*a43);
    a18=(a18+a43);
    if (res[0]!=0) res[0][6]=a18;
    a30=(a7*a30);
    a28=(a28+a30);
    a51=(a7*a51);
    a28=(a28+a51);
    a25=(a25-a58);
    a25=(a25/a29);
    a28=(a28+a25);
    a28=(a2*a28);
    a10=(a10+a28);
    if (res[0]!=0) res[0][7]=a10;
    a33=(a7*a33);
    a32=(a32+a33);
    a54=(a7*a54);
    a32=(a32+a54);
    a31=(a31-a41);
    a31=(a31/a29);
    a32=(a32+a31);
    a32=(a2*a32);
    a11=(a11+a32);
    if (res[0]!=0) res[0][8]=a11;
    a37=(a7*a37);
    a36=(a36+a37);
    a56=(a7*a56);
    a36=(a36+a56);
    a35=(a35-a48);
    a35=(a35/a29);
    a36=(a36+a35);
    a36=(a2*a36);
    a13=(a13+a36);
    if (res[0]!=0) res[0][9]=a13;
    a40=(a7*a40);
    a39=(a39+a40);
    a7=(a7*a57);
    a39=(a39+a7);
    a38=(a38-a0);
    a38=(a38/a29);
    a39=(a39+a38);
    a2=(a2*a39);
    a14=(a14+a2);
    if (res[0]!=0) res[0][10]=a14;
    a10=(a10+a11);
    a10=(a10+a13);
    a10=(a10+a14);
    a9=(a9*a10);
    a10=(a8*a9);
    a17=(a17*a3);
    a16=(a16+a17);
    a17=casadi_sq(a3);
    a19=(a19*a17);
    a16=(a16+a19);
    a20=(a20*a3);
    a20=tanh(a20);
    a16=(a16*a20);
    a10=(a10-a16);
    a8=(a8*a9);
    a9=cos(a18);
    a9=(a8*a9);
    a10=(a10+a9);
    a10=(a10/a21);
    if (res[1]!=0) res[1][0]=a10;
    a18=sin(a18);
    a8=(a8*a18);
    a8=(a8/a21);
    if (res[1]!=0) res[1][1]=a8;
    return 0;
}

CASADI_SYMBOL_EXPORT int kin6_model(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
    return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int kin6_model_alloc_mem(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT int kin6_model_init_mem(int mem) {
    return 0;
}

CASADI_SYMBOL_EXPORT void kin6_model_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int kin6_model_checkout(void) {
    return 0;
}

CASADI_SYMBOL_EXPORT void kin6_model_release(int mem) {
}

CASADI_SYMBOL_EXPORT void kin6_model_incref(void) {
}

CASADI_SYMBOL_EXPORT void kin6_model_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int kin6_model_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int kin6_model_n_out(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_real kin6_model_default_in(casadi_int i) {
    switch (i) {
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* kin6_model_name_in(casadi_int i) {
    switch (i) {
        case 0: return "[X, Y, phi, v_x, v_y, omega, delta, tau_FL, tau_FR, tau_RL, tau_RR]";
        case 1: return "[u_delta, u_tau_FL, u_tau_FR, u_tau_RL, u_tau_RR]";
        case 2: return "[m, I_z, l_R, l_F, C_m0, C_r0, C_r1, C_r2, t_tau, t_delta]";
        case 3: return "dt";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const char* kin6_model_name_out(casadi_int i) {
    switch (i) {
        case 0: return "x_next";
        case 1: return "[a_x, a_y]";
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* kin6_model_sparsity_in(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s1;
        case 2: return casadi_s2;
        case 3: return casadi_s3;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT const casadi_int* kin6_model_sparsity_out(casadi_int i) {
    switch (i) {
        case 0: return casadi_s0;
        case 1: return casadi_s4;
        default: return 0;
    }
}

CASADI_SYMBOL_EXPORT int kin6_model_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 4;
    if (sz_res) *sz_res = 2;
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 0;
    return 0;
}

CASADI_SYMBOL_EXPORT int kin6_model_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
    if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
    if (sz_res) *sz_res = 2*sizeof(casadi_real*);
    if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
    if (sz_w) *sz_w = 0*sizeof(casadi_real);
    return 0;
}

casadi_int main_kin6_model(casadi_int argc, char* argv[]) {
    casadi_int j;
    casadi_real* a;
    const casadi_real* r;
    casadi_int flag;
    casadi_int *iw = 0;
    casadi_real w[107];
    const casadi_real* arg[4];
    casadi_real* res[2];
    arg[0] = w+0;
    arg[1] = w+11;
    arg[2] = w+16;
    arg[3] = w+26;
    res[0] = w+27;
    res[1] = w+38;
    a = w;
    for (j=0; j<27; ++j) if (scanf("%lg", a++)<=0) return 2;
    flag = kin6_model(arg, res, iw, w+40, 0);
    if (flag) return flag;
    r = w+27;
    for (j=0; j<13; ++j) CASADI_PRINTF("%g ", *r++);
    CASADI_PRINTF("\n");
    return 0;
}

CASADI_SYMBOL_EXPORT casadi_functions* kin6_model_functions(void) {
    static casadi_functions fun = {
        kin6_model_incref,
        kin6_model_decref,
        kin6_model_checkout,
        kin6_model_release,
        kin6_model_default_in,
        kin6_model_n_in,
        kin6_model_n_out,
        kin6_model_name_in,
        kin6_model_name_out,
        kin6_model_sparsity_in,
        kin6_model_sparsity_out,
        kin6_model_work,
        kin6_model
    };
    return &fun;
}

CASADI_SYMBOL_EXPORT int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "kin6_model")==0) {
    return main_kin6_model(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'kin6_model'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
