on:
  pull_request:
    branches:
      - main
    types: [labeled]
  workflow_dispatch:

jobs:
  remove_workflow_label:
    name: Remove workflow label
    runs-on: ubuntu-latest
    if: github.event.label.name == 'ci:run_build'
    steps:
      - uses: actions/checkout@v4

      - name: Remove workflow label
        run: gh pr edit ${{ github.event.pull_request.number }} --remove-label "ci:run_build"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: github.event.label.name == 'ci:run_build'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "self-hosted"]
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Cleanup residual micromamba-installation
        run: rm -rf ~/micromamba-bin

      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: 1.5.12-0
          environment-name: brains2
          environment-file: conda-lock.yml
          init-shell: bash
          cache-environment: true

      - name: Build workspace
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh

      - name: Zip build output
        run: |
          zip -r output-${{ matrix.os }}.zip build install log

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.os }}
          path: output-${{ matrix.os }}.zip

  lint:
    name: Lint (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    if: github.event.label.name == 'ci:run_build'
    needs: build
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "self-hosted"]
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Cleanup residual micromamba-installation
        run: rm -rf ~/micromamba-bin

      - uses: mamba-org/setup-micromamba@v2
        with:
          micromamba-version: 1.5.12-0
          environment-name: brains2
          environment-file: conda-lock.yml
          init-shell: bash
          cache-environment: true

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: output-${{ matrix.os }}
          path: output-${{ matrix.os }}.zip

      - name: Unzip build output
        run: unzip output-${{ matrix.os }}.zip

      - name: Run lint and formatting checks
        run: |
          colcon test --ctest-args -E test
          colcon test-result --all --verbose
